import localFont from "next/font/local";

import { JetBrains_Mono, Poppins } from "next/font/google";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

import "@/styles/globals.css";
import "@/styles/md-content.css";
import { Separator } from "@/components/ui/separator";
import { getAllMarkdownFiles } from "@/lib/content";
import { buildFileTree } from "@/lib/utils";
import { AppBreadcrumb } from "@/components/app-breadcrumb";

const poppins = Poppins({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"]
});

const jetbrains = JetBrains_Mono({
  variable: "--font-jetbrains",
  display: "swap",
  subsets: ["latin"],
  weight: ["400"]
});

const arabic = localFont({
  src: "../assets/fonts/LPMQ Isep Misbah.woff2",
  variable: "--font-arabic"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  const allMarkdownFiles = getAllMarkdownFiles();
  const fileTree = buildFileTree(allMarkdownFiles);

  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-title" content="Open Notes" />
      </head>
      <body className={`${poppins.variable} ${jetbrains.variable} ${arabic.variable} antialiased`}>
        <SidebarProvider>
          <AppSidebar fileTree={fileTree} />
          <SidebarInset>
            <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4">
              <SidebarTrigger className="-ml-1" />
              <Separator orientation="vertical" className="mr-2 data-[orientation=vertical]:h-4" />
              <AppBreadcrumb allMarkdownFiles={allMarkdownFiles} />
            </header>
            <div className="flex flex-1 flex-col gap-4 p-4">
              <div className="min-h-[100vh] flex-1 rounded-xl border p-4 md:min-h-min">
                {children}
              </div>
            </div>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
