import localFont from "next/font/local";

import { JetBrains_Mono, Poppins } from "next/font/google";

import "./globals.css";

const poppins = Poppins({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

const jetbrains = JetBrains_Mono({
  variable: "--font-jetbrains",
  display: "swap",
  subsets: ["latin"],
  weight: ["400"],
});

const arabic = localFont({
  src: "../assets/fonts/LPMQ Isep Misbah.woff2",
  variable: "--font-arabic",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-title" content="Open Notes" />
      </head>
      <body
        className={`${poppins.variable} ${jetbrains.variable} ${arabic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
